# Deploy tagged releases.

name:  Deploy Release

on:
  push:
    tags:
      - '*'

# This is for debugging.
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}

jobs:
  wheels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: python3 -m pip install build twine numpy

    - name: Install Package
      run: python3 -m pip install .

    - name: Run Simple Test
      run: python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Build source package
      run: rm -rf dist && python3 -m build --sdist

    - name: Build wheels
      run: python3 -m build --wheel

    - name: Upload to PyPI
      run: |
        python -m twine upload dist/*.tar.gz && python -m twine upload dist/pshmem*.whl
