# Deploy tagged releases.

name:  Deploy Release

on:
  push:
    tags:
      - '*'

# This is for debugging.
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}

jobs:
  wheels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: ./test_scripts/install_deps_github_ubuntu.sh && pip install twine

    - name: Install Package
      run: pip install .

    - name: Run Serial Test
      run: MPI_DISABLE=1 python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Run MPI Test on 1 Process
      run: mpirun -np 1 python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Run MPI Test on 2 Processes
      run: mpirun -np 2 python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Build source package
      run: rm -rf dist && python setup.py sdist

    - name: Build wheels
      run: mkdir -p wheelhouse && pip wheel -w wheelhouse .

    - name: Upload to PyPI
      run: |
        python -m twine upload dist/*.tar.gz && python -m twine upload wheelhouse/pshmem*.whl
