# Deploy tagged releases.

name:  Deploy Release

on:
  workflow_dispatch:
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wheels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: python3 -m pip install build numpy

    - name: Install Package
      run: python3 -m pip install .

    - name: Run Simple Test
      run: python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Build source package
      run: rm -rf dist && python3 -m build --sdist

    - name: Build wheels
      run: python3 -m build --wheel

    - uses: actions/upload-artifact@v4
      with:
        name: pshmem
        path: ./dist/pshmem*.whl

  upload_pypi:
    needs: wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v5
        with:
          # Unpacks all artifacts into dist/
          pattern: pshmem-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
