# Deploy tagged releases.

name:  Deploy Release

on:
  push:
    tags:
      - '*'

# This is for debugging.
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

env:
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}

jobs:
  wheels:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Dependencies
      run: ./test_scripts/install_deps_github_ubuntu.sh && pip install twine

    - name: Install Package
      run: pip install .

    - name: Run Serial Test
      run: MPI_DISABLE=1 python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Run MPI Test on 1 Process
      run: mpirun -np 1 python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Run MPI Test on 2 Processes
      run: mpirun -np 2 python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Build source package
      run: rm -rf dist && python setup.py sdist

    - name: Build wheels
      run: mkdir -p wheelhouse && pip wheel -w wheelhouse .

    - name: Upload to PyPI
      run: |
        python -m twine upload dist/*.tar.gz && python -m twine upload wheelhouse/pshmem*.whl
