# Use pre-built docker containers to run our unit tests on different python versions.

name:  Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: ./test_scripts/install_deps_github_ubuntu.sh
    - name: Install Package
      run: pip3 install .
    - name: Run Serial Test
      run: MPI_DISABLE=1 python3 -c 'import pshmem.test; pshmem.test.run()'
    - name: Run MPI Test on 1 Process
      run: mpirun -np 1 python3 -c 'import pshmem.test; pshmem.test.run()'
    - name: Run MPI Test on 2 Processes
      run: mpirun -np 2 python3 -c 'import pshmem.test; pshmem.test.run()'
    - name: Run MPI Test on 4 Processes
      run: mpirun -np 4 python3 -c 'import pshmem.test; pshmem.test.run()'
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: ./test_scripts/install_deps_github_macos.sh
    - name: Install Package
      run: pip3 install .
    - name: Run Serial Test
      run: MPI_DISABLE=1 python3 -c 'import pshmem.test; pshmem.test.run()'
    - name: Run MPI Test on 1 Process
      run: mpirun -np 1 python3 -c 'import pshmem.test; pshmem.test.run()'
    - name: Run MPI Test on 2 Processes
      run: mpirun -np 2 python3 -c 'import pshmem.test; pshmem.test.run()'
    - name: Run MPI Test on 4 Processes
      run: mpirun -np 4 python3 -c 'import pshmem.test; pshmem.test.run()'
