# Use pre-built docker containers to run our unit tests on different python versions.

name:  Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.11", "3.12"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: ./test_scripts/install_deps_github_ubuntu.sh

    - name: Install Package
      run: pip3 install .

    - name: Run Serial Test
      run: MPI_DISABLE=1 python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Run MPI Test on 1 Process
      run: mpirun -np 1 python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Run MPI Test on 2 Processes
      run: mpirun -np 2 python3 -c 'import pshmem.test; pshmem.test.run()'

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: ./test_scripts/install_deps_github_macos.sh

    - name: Install Package
      run: pip3 install .

    - name: Run Serial Test
      run: MPI_DISABLE=1 python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Run MPI Test on 1 Process
      run: mpirun -np 1 python3 -c 'import pshmem.test; pshmem.test.run()'

    - name: Run MPI Test on 2 Processes
      run: mpirun -np 2 python3 -c 'import pshmem.test; pshmem.test.run()'
